package com.trustai.user_service.user.exception;


import com.trustai.user_service.user.exception.base.UserValidationException;

public class RecordNotFoundExceptionUser extends UserValidationException {
}
